=== fominvadim95/parsers/src/main/resources/teams.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Elements definition -->
    <xs:simpleType name="PlayerAge">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="16"/>
            <xs:maxInclusive value="45"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CoachAge">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="20"/>
            <xs:maxInclusive value="80"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Experience">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="40"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Cost">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="300"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Position">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CB"/>
            <xs:enumeration value="FB"/>
            <xs:enumeration value="CM"/>
            <xs:enumeration value="FM"/>
            <xs:enumeration value="F"/>
            <xs:enumeration value="G"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Year">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Capacity">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1000"/>
            <xs:maxInclusive value="200000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Info">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PlayerInfo">
        <xs:complexContent>
            <xs:extension base="Info">
                <xs:sequence>
                    <xs:element name="age" type="PlayerAge"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="CoachInfo">
        <xs:complexContent>
            <xs:extension base="Info">
                <xs:sequence>
                    <xs:element name="age" type="CoachAge"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="StadiumInfo">
        <xs:complexContent>
            <xs:extension base="Info">
                <xs:sequence>
                    <xs:element name="city" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Player">
        <xs:sequence>
            <xs:element name="general" type="PlayerInfo"/>
            <xs:element name="cost" type="Cost"/>
            <xs:element name="position" type="Position"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="Coach">
        <xs:sequence>
            <xs:element name="general" type="CoachInfo"/>
            <xs:element name="experience" type="Experience"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="Sponsor">
        <xs:sequence>
            <xs:element name="general" type="Info"/>
            <xs:element name="year" type="Year"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="Stadium">
        <xs:sequence>
            <xs:element name="general" type="StadiumInfo"/>
            <xs:element name="capacity" type="Capacity"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Team">
        <xs:sequence>
            <xs:element name="general" type="Info"/>

            <xs:element name="players">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="player" type="Player" minOccurs="1"
                                    maxOccurs="11"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="coach" type="Coach"/>

            <xs:element name="sponsors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="sponsor" type="Sponsor" minOccurs="1"
                                    maxOccurs="25"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="stadium" type="Stadium"/>

        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <!-- Elements manipulation -->
    <xs:element name="teams">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team" type="Team" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== fominvadim95/parsers/src/main/resources/xml/dom.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<teams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../xsd/teams.xsd">
    <team id="t1">
        <general>
            <name>Barcelona</name>
            <country>Spain</country>
        </general>
        <players>
            <player id="p1">
                <general>
                    <name>Messi</name>
                    <country>Argentina</country>
                    <age>29</age>
                </general>
                <cost>250</cost>
                <position>F</position>
            </player>
            <player id="p2">
                <general>
                    <name>Rakitic</name>
                    <country>Croatia</country>
                    <age>28</age>
                </general>
                <cost>70</cost>
                <position>CM</position>
            </player>
            <player id="p3">
                <general>
                    <name>Neymar</name>
                    <country>Brazil</country>
                    <age>25</age>
                </general>
                <cost>120</cost>
                <position>FM</position>
            </player>
        </players>
        <coach id="c1">
            <general>
                <name>Enrique</name>
                <country>Spain</country>
                <age>75</age>
            </general>
            <experience>5</experience>
        </coach>
        <sponsors>
            <sponsor id="audi">
                <general>
                    <name>Audi</name>
                    <country>Germany</country>
                </general>
                <year>2017</year>
            </sponsor>
            <sponsor id="estrella">
                <general>
                    <name>Estrella Damm</name>
                    <country>Spain</country>
                </general>
                <year>2022</year>
            </sponsor>
            <sponsor id="coca-cola">
                <general>
                    <name>Coca-Cola</name>
                    <country>USA</country>
                </general>
                <year>2019</year>
            </sponsor>
        </sponsors>
        <stadium id="s1">
            <general>
                <name>Camp Nou</name>
                <country>Spain</country>
                <city>Barcelona</city>
            </general>
            <capacity>99354</capacity>
        </stadium>
    </team>
</teams>

=== fominvadim95/parsers/src/main/resources/dom.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<teams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="teams.xsd">
    <team id="t1">
        <general>
            <name>Barcelona</name>
            <country>Spain</country>
        </general>
        <players>
            <player id="p1">
                <general>
                    <name>Messi</name>
                    <country>Argentina</country>
                    <age>29</age>
                </general>
                <cost>250</cost>
                <position>F</position>
            </player>
        </players>
        <coach id="c1">
            <general>
                <name>Enrique</name>
                <country>Spain</country>
                <age>75</age>
            </general>
            <experience>5</experience>
        </coach>
        <sponsors>
            <sponsor id="audi">
                <general>
                    <name>Audi</name>
                    <country>Germany</country>
                </general>
                <year>2011</year>
            </sponsor>
            <sponsor id="estrella">
                <general>
                    <name>Estrella Damm</name>
                    <country>Spain</country>
                </general>
                <year>2014</year>
            </sponsor>
        </sponsors>
        <stadium id="s1">
            <general>
                <name>Camp Nou</name>
                <country>Spain</country>
                <city>Barcelona</city>
            </general>
            <capacity>99354</capacity>
        </stadium>
    </team>
</teams>

=== fominvadim95/parsers/src/main/resources/xml/jaxb.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<teams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/teams.xsd">
    <team id="t1">
        <general>
            <name>Real Madrid</name>
            <country>Spain</country>
        </general>
        <players>
            <player id="p1">
                <general>
                    <name>Ronaldo</name>
                    <country>Portugal</country>
                    <age>32</age>
                </general>
                <cost>150</cost>
                <position>FB</position>
            </player>
        </players>
        <coach id="c1">
            <general>
                <name>Zidane</name>
                <country>France</country>
                <age>44</age>
            </general>
            <experience>7</experience>
        </coach>
        <sponsors>
            <sponsor id="sp1">
                <general>
                    <name>Emirates Airlines</name>
                    <country>UAE</country>
                </general>
                <year>2020</year>
            </sponsor>
        </sponsors>
        <stadium id="st1">
            <general>
                <name>Santiago Bernabeu</name>
                <country>Spain</country>
                <city>Madrid</city>
            </general>
            <capacity>81044</capacity>
        </stadium>
    </team>
</teams>
